---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: install nginx
      apt: name=nginx state=present
    - name: Ngninx configuration
      copy: src=/vagrant/default dest=/etc/nginx/sites-enabled/default
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started

