---
- hosts: frontofficeAPI
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: install git
      apt: name=git state=present
    - name: install script for nodejs
      script: /files/setup_node.sh
    - name: install nodejs
      apt: name=nodejs
    - name: clone git repo
      git: repo=https://github.com/Flasheur111/CocktailFinder.git dest=/home/vagrant/ update=no
